# Generated by Django 4.1.1 on 2022-09-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('subtitle', models.TextField(null=True)),
                ('image1', models.ImageField(null=True, upload_to='img/%y')),
                ('image2', models.ImageField(null=True, upload_to='img/%y')),
                ('desc', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('icon', models.ImageField(null=True, upload_to='img/%y')),
            ],
        ),
    ]
